#ifndef ESP_IDF_LIB_HELPERS_H
#define ESP_IDF_LIB_HELPERS_H

#include <sdkconfig.h>

#ifndef HELPER_TARGET_IS_ESP32
#define HELPER_TARGET_IS_ESP32 CONFIG_IDF_TARGET_ESP32
#endif

#ifndef HELPER_TARGET_IS_ESP8266
#ifdef CONFIG_IDF_TARGET_ESP8266
#define HELPER_TARGET_IS_ESP8266 CONFIG_IDF_TARGET_ESP8266
#else
#define HELPER_TARGET_IS_ESP8266 0
#endif
#endif

#endif // ESP_IDF_LIB_HELPERS_H
